'use client';

import { useState } from 'react';

interface ImageGalleryProps {
  images: Array<{ key: string; imageUrl: string }>;
  processing: boolean;
  onDownloadAll: () => void;
}

export default function ImageGallery({
  images,
  processing,
  onDownloadAll,
}: ImageGalleryProps) {
  const [expandedImage, setExpandedImage] = useState<string | null>(null);

  if (images.length === 0) return null;

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-2xl font-semibold">AI-Generated Room Scenes 🎨</h2>
        <button
          onClick={onDownloadAll}
          disabled={processing}
          className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition-colors flex items-center gap-2 disabled:opacity-50"
        >
          {processing ? '⏳ Creating ZIP...' : `📦 Download All (${images.length})`}
        </button>
      </div>
      <p className="text-gray-600 dark:text-gray-400 mb-4">
        Photorealistic room scenes showing your rugs in styled settings, generated by{' '}
        <strong>Gemini 2.5 Flash Image</strong>. Each image is created at 2K resolution
        (1792x1024px) with professional interior photography quality.
      </p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {images.map((image) => (
          <div key={image.key} className="space-y-2">
            <h3 className="font-medium text-sm text-gray-700 dark:text-gray-300">
              {image.key}
            </h3>
            <div
              className="border dark:border-gray-700 rounded-lg overflow-hidden cursor-pointer hover:ring-2 hover:ring-blue-400 transition-all"
              onClick={() => setExpandedImage(expandedImage === image.key ? null : image.key)}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={image.imageUrl}
                alt={`Rug scene ${image.key}`}
                className={`w-full h-auto transition-transform ${
                  expandedImage === image.key ? 'scale-100' : ''
                }`}
              />
            </div>
            <a
              href={image.imageUrl}
              download={`${image.key}-scene.png`}
              className="inline-block text-sm text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
            >
              Download Image
            </a>
          </div>
        ))}
      </div>

      {/* Lightbox for expanded image */}
      {expandedImage && (
        <div
          className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4"
          onClick={() => setExpandedImage(null)}
        >
          <div className="max-w-7xl max-h-full">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={images.find(i => i.key === expandedImage)?.imageUrl}
              alt={`Expanded: ${expandedImage}`}
              className="max-w-full max-h-[90vh] object-contain"
            />
          </div>
        </div>
      )}
    </div>
  );
}
